# junit5-gradle-consumer

The `junit5-gradle-consumer` project demonstrates how to run tests based on
the JUnit 5 prototype using Gradle with the help of a very basic `JUnit5Plugin`
that is currently inlined in the `build.gradle` script.

## Executing JUnit 5 Tests

Invoking `gradlew clean test` from the command line will execute all tests in
the `com.example.project` package and its subpackages as well as the
`com.example.project.AJUnit4Test` JUnit 4 based test, resulting in output
similar to the following:

```
Test execution started. Number of static tests: 3
Engine started: junit5
Test started:     My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test skipped:     mySecondTest [junit5:com.example.project.SecondTest#mySecondTest()]
                  => Exception:   Skipping test method [void com.example.project.SecondTest.mySecondTest()]; reason: @Disabled is present on test method [void com.example.project.SecondTest.mySecondTest()]
Engine finished: junit5
Engine started: junit4
Test started:     myJunit4Test(com.example.project.AJUnit4Test) [junit4:myJunit4Test(com.example.project.AJUnit4Test)]
Test succeeded:   myJunit4Test(com.example.project.AJUnit4Test) [junit4:myJunit4Test(com.example.project.AJUnit4Test)]
Engine finished: junit4
Test execution finished.

Test run finished after 52 ms
[         3 tests found     ]
[         2 tests started   ]
[         1 tests skipped   ]
[         0 tests aborted   ]
[         2 tests successful]
[         0 tests failed    ]
```

If you comment out the `@Disabled` annotation on `SecondTest#mySecondTest()`, you
will then see the build fail with output similar to the following:

```
Test execution started. Number of static tests: 3
Engine started: junit5
Test started:     My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test started:     mySecondTest [junit5:com.example.project.SecondTest#mySecondTest()]
Test failed:      mySecondTest [junit5:com.example.project.SecondTest#mySecondTest()]
                  => Exception:   2 is not equal to 1 ==> expected:<2> but was:<1>
Engine finished: junit5
Engine started: junit4
Test started:     myJunit4Test(com.example.project.AJUnit4Test) [junit4:myJunit4Test(com.example.project.AJUnit4Test)]
Test succeeded:   myJunit4Test(com.example.project.AJUnit4Test) [junit4:myJunit4Test(com.example.project.AJUnit4Test)]
Engine finished: junit4
Test execution finished.

Test run finished after 48 ms
[         3 tests found     ]
[         3 tests started   ]
[         0 tests skipped   ]
[         0 tests aborted   ]
[         2 tests successful]
[         1 tests failed    ]

:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Note**: the _exit value_ corresponds to the number of _tests failed_.

### Current Limitations

- The `JUnit5Plugin` task currently only executes tests in the `com.example.project` package and its subpackages.
- Even though the build will fail if a test fails, the results will not be included in the test report generated by Gradle.
